import time

name = input("请输入您的名字：")
if name == "ABC":
    key = input("请输入密码：")
    if key == "1314":
        print("欢迎您登入学生信息管理系统")
        time.sleep(1)
        def new_func():
            height = 5
            stars = 1
            for i in range(height):
                print((' ' * (height - i)) + ('*' * stars))
                stars += 2
            print((' ' * height) + '|')

        new_func()
        time.sleep(1)
        name2 = input("请输入您要查询的学生的姓名：")
        if name2 == "***":
            print("***，男，出生于****年5月")
            time.sleep(1)
            print("自我评价：****")
            time.sleep(1)
            print("好友评价：****")
            time.sleep(0.5)
            print("****")
            time.sleep(0.5)
            print(".")
            time.sleep(0.5)
            print("..")
            time.sleep(0.5)
            print("...")
            time.sleep(2)
            print('''检测到远程入侵
            正在关闭系统......''')
            time.sleep(1)
            print("系统关闭失败")
            time.sleep(0.5)
            print("管理员权限已转交给bananas12138")
            time.sleep(1)
            print("bananas12138正在上传文件")
            time.sleep(0.5)
            print("检测到该文件为一段给“ABC女士”的留言")
            open = input("您是否要打开该留言？")
            if open == "是":
                print("这是一段留言")
                input()
            else:
                open2 = input("是否确认关闭？")
                if open2 == "是":
                    print("对不起，谢谢你")
                    input()
                else:
                    print("这是一段留言")
                    input()
        else:
            print("抱歉，无法找到该学生的信息！")
            time.sleep(5)
            print("************")
            time.sleep(5)
            print('''出现错误！！！！
            系统已强制终止！！！''')
            input()
    else:
        print("密码错误，请向管理员索要动态登录密码")
        onekey = input("请输入动态登录码：")
        if onekey == "5201314" :
            print('''密码正确
            正在登入****学生信息管理系统......''')
            name2 = input("请输入您要查询的学生的姓名：")
            if name2 == "***":
                print("***，男，出生于****年5月")
                time.sleep(1)
                print("自我评价：****")
                time.sleep(1)
                print("好友评价：****")
                time.sleep(0.5)
                print("****")
                time.sleep(0.5)
                print(".")
                time.sleep(0.5)
                print("..")
                time.sleep(0.5)
                print("...")
                time.sleep(2)
                print('''检测到远程入侵
                正在关闭系统......''')
                time.sleep(1)
                print("系统关闭失败")
                time.sleep(0.5)
                print("管理员权限已转交给bananas12138")
                time.sleep(1)
                print("bananas12138正在上传文件")
                time.sleep(0.5)
                print("检测到该文件为一段给“ABC女士”的留言")
                open = input("您是否要打开该留言？")
                if open == "是":
                    print("这是一段留言")
                    input()
                else:
                    open2 = input("是否确认关闭？")
                    if open2 == "是":
                        print("对不起，谢谢你")
                        input()
                    else:
                        print("这是一段留言")
                        input()
            else:
                print("抱歉，无法找到该学生的信息！") 
        elif onekey == "iloveu" :
            print("检测到管理员核心授权码")
            time.sleep(1)
            print('''授权码正确
            正在登入学生信息管理系统......''')
            time.sleep(1)
            name2 = input("请输入您要查询的学生的姓名：")
            time.sleep(1)
            if name2 == "***":
                print("***，男，出生于****年5月")
                time.sleep(1)
                print("自我评价：****")
                time.sleep(1)
                print("好友评价：****")
                time.sleep(0.5)
                print("****")
                time.sleep(0.5)
                print(".")
                time.sleep(0.5)
                print("..")
                time.sleep(0.5)
                print("...")
                time.sleep(2)
                print('''检测到远程入侵
                正在关闭系统......''')
                time.sleep(1)
                print("系统关闭失败")
                time.sleep(0.5)
                print("管理员权限已转交给bananas12138")
                time.sleep(1)
                print("bananas12138正在上传文件")
                time.sleep(0.5)
                print("检测到该文件为一段给“ABC女士”的留言")
                open = input("您是否要打开该留言？")
                if open == "是":
                    print("这是一段留言")
                    input()
                else:
                    open2 = input("是否确认关闭？")
                    if open2 == "是":
                        print("对不起，谢谢你")
                        input()
                    else:
                        print("这是一段留言")
                        input()
            else:
                print("抱歉，无法找到该学生的信息！") 
                time.sleep(1)
                print("系统已进入保护模式")
                time.sleep(1)
                print("系统将于十秒后关闭")
                time.sleep(1)
                print("系统将于九秒后关闭")
                time.sleep(1)
                print("系统将于八秒后关闭")
                time.sleep(1)
                print("系统将于七秒后关闭")
                time.sleep(1)
                print("系统将于六秒后关闭")
                time.sleep(1)
                print("系统将于五秒后关闭")
                time.sleep(1)
                print("系统将于四秒后关闭")
                time.sleep(1)
                print("系统将于三秒后关闭")
                time.sleep(1)
                print("系统将于二秒后关闭")
                time.sleep(1)
                print("系统将于一秒后关闭")
                time.sleep(1)
                print("系统关闭")
                time.sleep(0.5)
        else:
            print('''密码错误，无法登入，已自动上报管理员
                  正在为您联系管理员......''')
            time.sleep(1)
            print('''        无法联系管理员......
                  正在重试......''')
            time.sleep(2)
            print("重试失败！请您手动联系管理员！")
            time.sleep(2)
            input('''系统即将关闭
               若有需要请重新启动''')
            time.sleep(1)
            print("系统已进入保护模式")
            time.sleep(1)
            print("系统将于十秒后关闭")
            time.sleep(1)
            print("系统将于九秒后关闭")
            time.sleep(1)
            print("系统将于八秒后关闭")
            time.sleep(1)
            print("系统将于七秒后关闭")
            time.sleep(1)
            print("系统将于六秒后关闭")
            time.sleep(1)
            print("系统将于五秒后关闭")
            time.sleep(1)
            print("系统将于四秒后关闭")
            time.sleep(1)
            print("系统将于三秒后关闭")
            time.sleep(1)
            print("系统将于二秒后关闭")
            time.sleep(1)
            print("系统将于一秒后关闭")
            time.sleep(1)
            print("系统关闭")
            time.sleep(0.5)
elif name == "admin":
    print("welcome,Admin!")
elif name == "***":
    print("请输入系统PIN码")
    dikey = input("提示：PIN码为三个英文字母")
    if dikey == "123":
        print("欢迎您，管理员")
    else:
        time.sleep(1)
        print("已检测到入侵！！")
        time.sleep(1)
        print("系统已强制关闭")
        time.sleep(1)
        print("系统已关闭登陆通道！！")
        time.sleep(2)
        print("错误日志已上报管理员！")
else:
    print("用户名错误，无法登入，已自动上报管理员")
    time.sleep(1)
    print("系统已进入保护模式")
    time.sleep(1)
    print("系统将于十秒后关闭")
    time.sleep(1)
    print("系统将于九秒后关闭")
    time.sleep(1)
    print("系统将于八秒后关闭")
    time.sleep(1)
    print("系统将于七秒后关闭")
    time.sleep(1)
    print("系统将于六秒后关闭")
    time.sleep(1)
    print("系统将于五秒后关闭")
    time.sleep(1)
    print("系统将于四秒后关闭")
    time.sleep(1)
    print("系统将于三秒后关闭")
    time.sleep(1)
    print("系统将于二秒后关闭")
    time.sleep(1)
    print("系统将于一秒后关闭")
    time.sleep(1)
    print("系统关闭")
    time.sleep(0.5)